# Netlify configuration for SPA routing
[build]
  publish = "dist"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# Redirect all requests to index.html for client-side routing (SPA)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
